### ISSUE TITLE
Trying to get the AngularJS injector before it being set

### ISSUE THREAD

**Issue by viros** [ui-router/sample-app-angular-hybrid#10]
Got latest version.
npm install
npm start

See error: 
Trying to get the AngularJS injector before it being set. ; Zone: <root> ; Task: Promise.then ; Value: Error: Trying to get the AngularJS injector before it being set.

**Comment by stefanmeschke** [comment]
Hey @viros,

I have the same issue. Do you found any solution for this?

Cheers

**Comment by christopherthielen** [comment]
@viros @stefanmeschke @marcusreese @kucharskimaciej @catchshyam @zazmaister

Can you please try again?  I've added cypress e2e tests in this repository that should catch this sort of thing in the future.

```
git clone git@github.com:ui-router/sample-app-angular-hybrid.git
cd sample-app-angular-hybrid
npm install
npm start
```
