### ISSUE TITLE
Angular states doesn't work

### ISSUE THREAD

**Issue by ashwinaggarwal** [ui-router/sample-app-angular-hybrid#9]
Cloned the project, and installed the dependencies, but `/contacts` and `/prefs` state are not resolved, and the user is redirected to `/welcome`. Even the visualizer doesn't show the  contacts and prefs state.

package.json
```
"@uirouter/angular-hybrid": "^3.1.4"
"angular": "^1.6.6"
"@angular/common": "^4.0.0",
 "@angular/compiler": "^4.0.0",
"@angular/core": "^4.0.0",
"@angular/forms": "^4.0.0",
"@angular/http": "^4.0.0",
"@angular/platform-browser": "^4.0.0",
"@angular/platform-browser-dynamic": "^4.0.0",
"@angular/router": "^4.0.0",
"@angular/upgrade": "^4.0.0"
```
<img width="1278" alt="screen shot 2017-08-31 at 17 33 48" src="https://user-images.githubusercontent.com/5618454/29931815-a1fcb094-8e72-11e7-96b0-74bbc4742084.png">

**Comment by leosun1221** [comment]
same + 1

**Comment by leosun1221** [comment]
Remove angular-ui-router (or @uirouter/angularjs) from your package.json and replace it with @uirouter/angular-hybrid. Add the @angular/* dependencies.

I removed those two then working:
@uirouter/angular": "^1.0.0-beta.7"
@uirouter/angularjs": "^1.0.6"

**Comment by christopherthielen** [comment]
I'm not sure what the original issue was, but the sample app should be working now.  I tested locally and had no problems

```
git clone git@github.com:ui-router/sample-app-angular-hybrid.git
cd sample-app-angular-hybrid
npm install
npm start
```
